version: '3.9'

services: 
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: 
      - "15672:15672"
      - "5672:5672"
      - "5673:5673"

  redis-server:
    image: redis:latest
    restart: always

  server:
    build: ./CodeBox-main
    restart: always
    ports: 
      - "3300:3300"

  worker:
    build: ./CodeBox-worker
    restart: always
    pids_limit: 50
    init: true
    mem_limit: 150M
